{% set version = "0.1.5" %}
{% set python_min = python_min | default("3.9") %}
{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: urljsf
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/urljsf/urljsf-{{ version }}.tar.gz
  sha256: 7d518ad2725b995248fafeddaf3e77b879a172ee12ed910f73894e24dd07c3cc

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - urljsf = urljsf.cli:main

requirements:
  host:
    - flit-core >=3.9.0,<4.0.0
    - pip
    - python {{ python_min }}
  run:
    - jinja2
    - jsonschema >=4.18
    - python >={{ python_min }}
    - tomli
    - typing_extensions >=4.0.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - urljsf
  commands:
    - pip check
    - urljsf --version
    - urljsf --help

outputs:
  - name: urljsf

  - name: urljsf-with-yaml
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("urljsf", max_pin="x.x.x") }}
        - ruamel.yaml
    test:
      requires:
        - pip
      imports:
        - urljsf
      commands:
        - pip check
        - urljsf --version
        - urljsf --help

  - name: urljsf-with-sphinx
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("urljsf", max_pin="x.x.x") }}
        - sphinx >=6.1
    test:
      requires:
        - pip
      imports:
        - urljsf
      commands:
        - pip check
        - urljsf --version
        - urljsf --help

  - name: urljsf-with-mkdocs
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("urljsf", max_pin="x.x.x") }}
        - mkdocs >=1.5.0
        - pymdown-extensions >=10.11.0
    test:
      requires:
        - pip
      imports:
        - urljsf
      commands:
        - pip check
        - urljsf --version
        - urljsf --help

  - name: urljsf-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("urljsf", max_pin="x.x.x") }}
        - {{ pin_subpackage("urljsf-with-yaml", max_pin="x.x.x") }}
        - {{ pin_subpackage("urljsf-with-sphinx", max_pin="x.x.x") }}
        - {{ pin_subpackage("urljsf-with-mkdocs", max_pin="x.x.x") }}
    test:
      source_files:
        - pyproject.toml
        - tests
      requires:
        - pip
        - pytest-console-scripts
        - pytest-cov
        - pytest-html
        - tomli-w
      imports:
        - urljsf
      commands:
        - pip check
        - urljsf --version
        - urljsf --help
        - pytest -vv --color=yes --tb=long --cov=urljsf --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=97

about:
  home: https://github.com/deathbeds/urljsf
  summary: Build declarative, interactive HTML forms with JSON Schema
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - src/urljsf/_static/urljsf/third-party-licenses.json
  doc_url: https://urljsf.rtfd.org

extra:
  feedstock-name: urljsf
  recipe-maintainers:
    - bollwyvl
